/*delete from tech_page_tech_page_role ;*/
insert into tech_page_tech_page_role
select * from  (
select :page_id page_id,1 role_id from  dual union
select :page_id,2 from  dual union
select :page_id,3 from  dual union
select :page_id,4 from  dual union
select :page_id,5 from  dual union
select :page_id,6 from  dual union
select :page_id,7 from  dual union
select :page_id,8 from  dual union
select :page_id,9 from  dual union
select :page_id,10 from  dual union
select :page_id,11 from  dual

) s


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE arkani_1.tech_page_role (
	id BIGINT NOT NULL,
	`method` VARCHAR(255) NULL,
	`role` VARCHAR(255) NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE arkani_1.tech_page (
	id BIGINT NOT NULL  NOT NULL AUTO_INCREMENT,
	active_row INT NOT NULL,
	order_row INT NOT NULL,
	project VARCHAR(255) NULL,
	name VARCHAR(255) NULL,
	url VARCHAR(255) NULL,
	tag VARCHAR(255) NULL,
	button VARCHAR(255) NULL,
	description VARCHAR(255) NULL,
	header VARCHAR(255) NULL,
	content VARCHAR(255) NULL,
	PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



alter table tech_page
       add constraint FK9qyadyq62mbt11o9kw9wck5uq
       foreign key (role_id)
       references tech_page_role (id)


insert into arkani_1.tech_page

select * from arkani_1.tech_strona


select * from arkani_1.tech_page ;
select * from arkani_1.tech_page_role ;

select * from ;

select * from TV_kanaly;
select * from  ;
select * from arkani_1.tech_page

alter table  arkani_1.tech_page rename column roles to roles_old

create table arkani_1.tech_page_copy as select * from arkani_1.tech_page

alter table  arkani_1.tech_page  drop tech_page_role_id
select * from arkani_1.tech_page;
select * from arkani_1.tech_page_role;


drop table tech_page_role
select * from  tech_page_role
drop table arkani_1.tech_page;

CREATE TABLE arkani_1.tech_page (
	id BIGINT NOT NULL,
	acyive_row INT NOT NULL,
	order_row INT NOT NULL,
	project VARCHAR(255) NULL,
	name VARCHAR(255) NULL,
	url VARCHAR(255) NULL,
	tag VARCHAR(255) NULL,
	button VARCHAR(255) NULL,
	description VARCHAR(255) NULL,
	header VARCHAR(255) NULL,
	content VARCHAR(255) NULL

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

drop table arkani_1.tech_page;
CREATE TABLE arkani_1.tech_page (
	id BIGINT NOT NULL,
    project VARCHAR(255) NULL,
	name VARCHAR(255) NULL,

	url VARCHAR(255) NULL,
	tag VARCHAR(255) NULL,

	button VARCHAR(255) NULL,
	description VARCHAR(255) NULL,
	header VARCHAR(255) NULL,
	content VARCHAR(255) NULL

)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;



alter table arkani_1.tech_page  rename column acyive_row to active_row

GRANT SELECT (roles), INSERT (roles),update (roles) ON arkani_1.tech_page TO arkani;

update arkani_1.tech_page  set button = upper(button)
select * from arkani_1.tech_page
drop view arkani_1.tech_page_v
create view arkani_1.tech_page_v as select * from arkani_1.tech_page where active_row=1 order order_row,name

insert into arkani_1.tech_page (id, acyive_row, order_row, project, name, url, tag, button, description, header, content)
SELECT id, acyive_row, order_row, project, name, url, tag, button, description, header, content
FROM arkani_1.tech_page_copy;


insert into user
select * from user  where username='arkani2'
select * from  tech_page;

update tech_page set roles=  'ROLE_USER'
update tech_page set roles= concat('ROLE_ADMIN',' ',roles)
update tech_page set roles= concat('ROLE_GUEST',' ',roles) where id in (8,11,12)

select * from user



SELECT s.* FROM tech_page s  where active_Row=1 and name=:name and tag regexp "wy"  order by order_Row,name
SELECT s.* FROM tech_page s  where active_Row=1  and  tag regexp 'wy'  order by order_Row,name
